### ISSUE TITLE
Release tags?

### ISSUE THREAD

**Issue by miketheman** [hoxu/gitstats#29]
Any chance you could create a 'release' or tag with the current stable version?
The 'homebrew' project uses these to help with installation.

There's been a couple open requests for this over time, and it would behelpful to the users at large.

https://github.com/Homebrew/homebrew/pull/25447
https://github.com/Homebrew/homebrew/pull/14418

Thanks!

**Comment by bjornfor** [comment]
+1 (I was about to make an issue about this myself). I'm planning to package it for NixOS/nixpkgs.

**Comment by hoxu** [comment]
I could tag every single commit that goes into master, yes, but I don't honestly see the benefit in that. The master branch of gitstats is as stable as it gets.

Does NixOS require tags for packaging from git?

**Comment by bjornfor** [comment]
No, NixOS does not require git tags. It's just a preference of mine to have version numbers, something that signals "this is ready for downstream/users". If upstreams don't provide releases, we tend to use the YYYY-MM-DD as version number for the package.

I just mentioned NixOS/nixpkgs because I think releases and tags makes more sense from a package manager view point. If I was to just clone this repo and build it manually out of the source tree, I probably wouldn't care that much about tags or releases.

**Comment by miketheman** [comment]
This is now available via homebrew head-only. https://github.com/Homebrew/homebrew-head-only
