### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by bfontaine** [hoxu/gitstats#58]
Hello,

It’d be great if you could tag a stable release so we can use the GitHub-generated tarball instead of relying on the git `HEAD` commit.

Thanks!

**Comment by hoxu** [comment]
The way gitstats has been maintained for a while now, is that every commit in master is basically a stable release. I don't see much sense in tagging every commit, and homebrew is the only downstream that cares about tags (at least was last time I reached out to other packagers). Tags are only good as an indication to downstreams on what to package, and in case of gitstats, I want downstreams to package the master branch.

I love homebrew, but to be honest, I don't understand why the project insists on having tags. Why not allow fixing directly to revisions, if you want full control over when the homebrew package is updated?

(And seeing the comment on Homebrew/homebrew-head-only/issues/186 about lacking automatic update mechanism, perhaps that's something that should be fixed in homebrew?)

**Comment by bfontaine** [comment]
> Why not allow fixing directly to revisions, if you want full control over when the homebrew package is updated?

A tag is like a release; we considere that unreleased software is (usually) not considered stable enough by upstream. Thank you for the clarification regarding `gitstats`; I’ll ping other maintainers to see what we can do here.

> (And seeing the comment on Homebrew/homebrew-head-only#186 about lacking automatic update mechanism, perhaps that's something that should be fixed in homebrew?)

That’s true; we’re thinking about it.

**Comment by bjornfor** [comment]
I, as a NixOS packager, would also like to have tags/releases, as an indication that the software is "ready". This repo may be able to guarantee that every commit is stable enough to be consumed downstream, but in general that's very hard to achieve. If you don't want to tag every commit, how about tagging once or twice a year? (Time based release instead of feature based.)
